config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#top'

# Usersコントローラルーティング
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  get 'users/withdraw_view'
  patch '/users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
  patch '/users/:id/admin' => 'users#admin', as: 'user_admin'
  get '/users/admin_show' => 'users#admin_show', as: 'user_admin_show'
  resources :users, only: [:index, :show, :edit, :update]

# Postsコントローラルーティング
  get 'posts/top'
  get 'posts/about'
  get 'posts/hashtag'
  get 'posts/search_result'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
  end

# Albumsコントローラルーティング
  resources :albums, only: [:index, :show, :create, :destroy] do
    post 'posts/:id' => 'posts#album_in', as: 'posts_album_in'
    delete 'posts/:id' => 'posts#album_out', as: 'posts_album_out'
  end

# Roomsコントローラルーティング
  resources :rooms, only: [:index, :show, :create, :destroy]

# Contactsコントローラルーティング
  resources :contacts, only: [:new, :index, :show, :update, :create, :destroy]

# Relationshipsコントローラルーティング
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :albums, dependent: :destroy
  has_many :rooms
  has_many :messages
  has_many :contacts, dependent: :destroy

  has_many :active_relationships, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
  has_many :passive_relationships, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name, presence: true, length: { maximum: 12 }
  validates :introduction, length: { maximum: 100 }
  validates :status, inclusion: { in: [true, false] }
  validates :admin, inclusion: { in: [true, false] }

# 論理削除したユーザアカウントをログインできなくする
  def active_for_authentication?
      super && self.status?
  end

# フォローするメソッド
  def follow(other_user)
    unless self == other_user
      following << other_user
    end
  end

# フォロー解除のメソッド
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

# フォローしているかどうかを確認するメソッド
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # カレントユーザとアドミンのみ可能なアクション
  before_action :correct_user, only:[:edit, :update, :withdraw]
  # アドミンのみ可能なアクション
  before_action :require_admin, only:[:index, :admin, :admin_show]


  def show
    @user = User.find(params[:id])
    @albums = Album.where(user_id: @user.id).all
    if @user.admin == false
      if @user == current_user
        @current_user = User.find(current_user.id)
        @follow_users = @current_user.following.all
        @timeline_posts = Post.where(user_id: @follow_users).order(created_at: :desc)
      end
    else
      if current_user.admin == true
        redirect_to user_admin_show_path
      else
        redirect_to user_path(current_user.id)
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:success] = 'ユーザ情報を編集しました'
    else
      @user.errors.full_messages.each do |msg|
        flash[:danger] = msg
      end
      redirect_to user_path(@user.id)
    end
  end

  def index
    @users = User.page(params[:page]).per(20)
  end

  def withdraw
    if current_user.update(status: false)
      flash[:danger] = '退会しました'
      redirect_to root_path
    else
      flash[:danger] = "退会に失敗しました"
      render :withdraw
    end
  end

  def admin
    user = User.find(params[:id])
    if user.admin == false
      user.update(admin: true)
      redirect_to users_path
    else
      user.update(admin: false)
      redirect_to users_path
    end
  end

  def admin_show
    @unreplied_contacts = Contact.where(reply: nil).all
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :password, :password_confirmation, :email, :status, :admin)
  end

  def correct_user
    if user_signed_in?
      user = User.find(params[:id])
      if user != current_user && current_user.admin == false
        redirect_to user_path(current_user.id)
      end
    else
      redirect_to root_path
    end
  end

  def require_admin
    if user_signed_in?
      if current_user.admin == false
        redirect_to user_path(current_user.id)
      end
    else
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_albums.html.erb
<div class="container-fluid albums">
	<div class="row">
		<div class="col-md-offset-1 col-md-8">
			<% if @albums.exists? %>
				<% @albums.order(created_at: :desc).each do |album| %>
				    <%= link_to album_path(album.id), data: {"turbolinks" => false}, class:"album-link" do %>
						<div class="album-box">
							<div class="album-name">
							    <h2><%= album.name %></h2>
						    </div>
						    <div class="album-image">
						    	<% album.posts.first(3).each do |post| %>
								<%= attachment_image_tag post, :post_image, :fill, 100, 100, format:"jpg", fallback:"/images/no_image.jpg", size:"100x100", alt:"ユーザイメージ" %>
								<% end %>
						    </div>
						    <div class="album-post">
								<h3>計 <%= album.posts.count %> 枚</h3>
							</div>
						</div>
					<% end %>
				<% end %>
		    <% else %>
		        <h4>アルバムを作成していません</h4>
		    <% end %>
		</div>
	</div>
</div>

app/views/users/_edit.html.erb
<!-- ユーザプロフィール画像からのユーザ詳細（モーダル） -->
<div id="user-show" class="modal-text">
    <h3>Profile</h3>
    <p class="pull-right"><a class="user-show-close" id="modal-close"><i class="fas fa-times"></i></a></p>
    <div class="container-fluid modal-box">
    	<div class="row">
    		<%= form_for @user, url: user_path(@user.id)  do |f| %>
    		<div class="col-md-offset-1 col-md-2">
    			<%= attachment_image_tag @user, :profile_image, :fill, 150, 150, format: 'jpg', fallback: '/images/no_image.jpg', size:'150x150', class:"img-circle modal-img-user", alt:"ユーザイメージ" %>
    		</div>
    		<div class="col-md-offset-1 col-md-6">
			    <div class="modal-field">
			        <%= f.label :name, "ユーザ名" %>
                    <%= f.text_field :name, autocomplete: "name", readonly: true, class:"form-control" %>
                </div>
                <div class="modal-field">
				    <%= f.label :email, "E-mail" %>
				    <%= f.email_field :email, autocomplete: "email", readonly: true, class:"form-control" %>
			    </div>
			    <div class="modal-field">
				    <%= f.label :introduction, "紹介文" %>
				    <%= f.text_area :introduction, autocomplete: "introduction", readonly: true, class:"form-control" %>
			    </div>
			    <% end %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-offset-9 col-md-3">
				<button class="btn-success-user modal-switch" data-target="user-edit">編集する</button>
			</div>
		</div>
	</div>
</div>

<!-- ユーザ編集（モーダル） -->
<div id="user-edit" class="modal-text">
    <h3>Profile編集</h3>
    <p class="pull-right"><a class="user-show-close" id="modal-close"><i class="fas fa-times"></i></a></p>
    <div class="container-fluid modal-box">
    	<div class="row">
    		<%= form_for @user, url: user_path(@user.id)  do |f| %>
    		<div id="error_message">
    			<%= render "devise/shared/error_messages", resource: @user %>
    		</div>

    		<div class="col-md-offset-1 col-md-2">
    			<%= attachment_image_tag @user, :profile_image, :fill, 150, 150, format: 'jpg', fallback: '/images/no_image.jpg', size:'150x150', class:"img-circle modal-img-user", alt:"ユーザイメージ" %>
    			<div><img id="user_img_prev" src="#" class='hidden img-circle' ></div>
    			<%= f.attachment_field :profile_image, class:"select-profile-image" %>
    		</div>
    		<div class="col-md-offset-1 col-md-6">
			    <div class="modal-field">
			        <%= f.label :name, "ユーザ名" %>
                    <%= f.text_field :name, autocomplete: "name", class:"form-control" %>
                </div>
                <div class="modal-field">
				    <%= f.label :email, "E-mail" %>
				    <%= f.email_field :email, autocomplete: "email", class:"form-control" %>
			    </div>
			    <div class="modal-field">
				    <%= f.label :introduction, "紹介文" %>
				    <%= f.text_area :introduction, autocomplete: "introduction", class:"form-control" %>
			    </div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3">
				<%= link_to "退会", users_withdraw_view_path, data: {"turbolinks" => false}, class:"btn-withdrawuser" %>
			</div>
			<div class="col-md-offset-5 col-md-4">
				<span class="btn-success-user modal-switch" data-target="user-show">キャンセル</span>
				<%= f.submit "保存", class:"btn-success-user" %>
			<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/_favorites.html.erb
<div class="container-fluid user_posts">
	<div class="row">
		<div class="col-md-12">
			<% if @user.favorites.exists? %>
				<% @user.favorites.each do |favorite| %>
				    <% post = Post.find_by(id: favorite.post_id) %>
				    <div class="post">
				    	<%= link_to post_path(post.id), data: {"turbolinks" => false} do %>
							<%= attachment_image_tag post, :post_image, format:"jpg", fallback:"/images/no_image.jpg", class:"post-img", alt:"ポストイメージ" %>
						<% end %>
					</div>
				<% end %>
			<% else %>
			    <div class="col-md-offset-1">
			    	<h4>いいねした投稿はありません</h4>
			    </div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/_follow.html.erb
<% if user_signed_in? %>
	<% unless current_user == @user %>
		<% if current_user.following?(@user) %>
			<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }) do |f| %>
			    <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
			<% end %>
		<% else %>
			<%= form_for(current_user.active_relationships.build) do |f| %>
			    <%= hidden_field_tag :followed_id, @user.id %>
			    <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/users/_followers.html.erb
<div class="container-fluid followers">
	<div class="row">
		<div class="col-md-offset-1 col-md-7">
			<% if @user.followers.exists? %>
				<% @user.followers.each do |follower| %>
					<div class="list">
				    	<%= link_to user_path(follower.id), data: {"turbolinks" => false}, class:"list" do%>
							<%= attachment_image_tag follower, :profile_image, :fill, 80, 80, format:"jpg", fallback:"/images/no_image.jpg", size:"80x80", class:"img-circle", alt:"ユーザイメージ" %>
							<%= follower.name %>
						<% end %>
					</div>
				<% end %>
		    <% else %>
		        <h4>ユーザにフォローされていません</h4>
		    <% end %>
		</div>
	</div>
</div>

app/views/users/_following.html.erb
<div class="container-fluid following">
	<div class="row">
		<div class="col-md-offset-1 col-md-7">
			<% if @user.following.exists? %>
				<% @user.following.each do |following| %>
					<div class="list">
				    	<%= link_to user_path(following.id), data: {"turbolinks" => false}, class:"list" do%>
							<%= attachment_image_tag following, :profile_image, :fill, 80, 80, format:"jpg", fallback:"/images/no_image.jpg", size:"80x80", class:"img-circle", alt:"ユーザイメージ" %>
							<%= following.name %>
						<% end %>
					</div>
				<% end %>
			<% else %>
			    <h4>ユーザをフォローしていません</h4>
			<% end %>
		</div>
	</div>
</div>

app/views/users/_posts.html.erb
<div class="container-fluid user_posts">
	<div class="row">
		<div class="col-md-12">
			<% if @user.posts.exists? %>
				<% @user.posts.order(created_at: :desc).each do |post| %>
				    <div class="post">
				    	<%= link_to post_path(post.id), data: {"turbolinks" => false} do %>
							<%= attachment_image_tag post, :post_image, format:"jpg", fallback:"/images/no_image.jpg", class:"post-img", alt:"ポストイメージ" %>
						<% end %>
					</div>
				<% end %>
			<% else %>
			    <div class="col-md-offset-1">
			    	<h4>投稿はありません</h4>
			    </div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/admin_show.html.erb
<div class="container admin-show">
	<div class="row">
		<div class="col-md-12">
			<h1 class="heading">管理者ページ</h1>
		</div>

		<div class="col-md-4">
			<div class="sidebar">
				<ul>
					<li><%= link_to "ユーザ一覧", users_path, data: {"turbolinks" => false} %></li>
					<li><%= link_to "投稿一覧", posts_path, data: {"turbolinks" => false} %></li>
					<li><%= link_to "トークルーム一覧", rooms_path, data: {"turbolinks" => false} %></li>
					<li><%= link_to "コンタクト一覧", contacts_path, data: {"turbolinks" => false} %></li>
				</ul>
			</div>
		</div>

		<div class="col-md-8">
			<div class="unreplied_contacts">

				<% if @unreplied_contacts %>
					<table class="table contactindex">
						<thead>
							<tr>
								<th>ユーザ名</th>
								<th>本文</th>
								<th>日時</th>
								<th>回答</th>
							</tr>
						</thead>
						<tbody>
							<% @unreplied_contacts.order(created_at: :asc).each do |contact| %>
							<tr>
								<td><%= link_to user_path(contact.user.id), data: {"turbolinks" => false} do %><%= contact.user.name %><% end %></td>
								<td><%= link_to contact_path(contact.id), data: {"turbolinks" => false} do %><%= contact.content %><% end %></td>
								<td><%= link_to contact_path(contact.id), data: {"turbolinks" => false} do %><%= contact.created_at.strftime('%Y/%m/%d %H:%M') %><% end %></td>
								<td>
									<% if contact.reply? %>
										<%= link_to contact_path(contact.id), data: {"turbolinks" => false} do %><%= contact.updated_at.strftime('%Y/%m/%d %H:%M') %><% end %>
									<% else %>
										<%= link_to contact_path(contact.id), data: {"turbolinks" => false} do %>回答する<% end %>
									<% end %>
								</td>
							</tr>
							<% end %>
					    </tbody>
					</table>
				<% else %>
					<h2 class="no-contact">未回答の問い合わせはありません</h2>
				<% end %>
			</div>
		</div>

	</div>
</div>

app/views/users/error.js.erb
$('.error-message').html("<%= j(render 'devise/shared/error_messages', resource: @user) %>");

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<h2 class="userindex-title">ユーザ一覧</h2>

			<table class="table userindex">
				<thead>
					<tr>
						<th>ユーザID</th>
						<th>ユーザ名</th>
						<th>ステータス</th>
						<th></th>
						<th>権限</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= user.id %></td>
						<td class="name"><%= link_to user_path(user.id), data: {"turbolinks" => false} do %><%= user.name %><% end %></td>
						<td><% if user.status == false %>（退会済み）<% end %></td>
						<td><% if user.admin == false && user.status == true %><%= link_to "強制退会", user_withdraw_path(user.id), method: :patch, data:{confirm:"本当に退会させますか?", "turbolinks" => false} %><% end %></td>
						<td><% if user.admin == true %>管理者<% end %></td>
						<td><% if user.admin == false %><%= link_to "管理者にする", user_admin_path(user.id), method: :patch, data:{confirm:"本当に管理者にしますか?", "turbolinks" => false} %>
							<% else %><%= link_to "ユーザにする", user_admin_path(user.id), method: :patch, data:{confirm:"本当にユーザにしますか?", "turbolinks" => false} %>
							<% end %></td>
					</tr>
					<% end %>
			    </tbody>
			</table>

			<div class="row" style="text-align: center;">
				<%= paginate @users %>
			</div>

		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-3">
			<div class="user-profileimage">
				<% if @user == current_user %>
					<%= attachment_image_tag @user, :profile_image, format: 'jpg', fallback: '/images/no_image.jpg', class:"img-circle img-user", id:"modal-open", "data-target":"user-show", alt:"ユーザイメージ" %>
				<% else %>
				    <%= attachment_image_tag @user, :profile_image, format: 'jpg', fallback: '/images/no_image.jpg', class:"img-circle img-user", alt:"ユーザイメージ" %>
				<% end %>
		    </div>
		    <div class="follow">
			    <a href="#tab2" class="count"><h4>フォロー <%= @user.following.count %></h4></a>
			    <a href="#tab3" class="count"><h4> フォロワー <%= @user.followers.count %></h4></a>
			    <%= render 'users/follow' %>
			</div>
		</div>
		<div class="col-md-7">
			<div class="user-name">
				<%= @user.name %>
			</div>
			<div class="user-introduction">
				<%= @user.introduction %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-offset-1 col-md-3">

			<% if @user == current_user %>
				<div class="timeline">
					<div class="timeline-box">
						<div class="timeline-heading">
							<h4><i class="far fa-clipboard"></i> タイムライン</h4>
						</div>
						<% if @timeline_posts.exists? %>
							<% @timeline_posts.first(5).each do |timeline_post| %>
							    <div class="timeline-post">
							    	<%= link_to post_path(timeline_post.id), data: {"turbolinks" => false} do %><%= attachment_image_tag timeline_post, :post_image, format:"jpg", fallback:"/images/no_image.jpg", class:"timeline-post-image", alt:"ポストイメージ" %><% end %>
							    </div>
							<% end %>
						<% else %>
						    <p class="no-timeline">ユーザをフォローしていません</p>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
		<div class="col-md-8">
			<nav class="navbar navbar-default bg-dark mypage-nav">
				<div class="container-fluid">
					<ul class="nav navbar-nav" id="tab-menu">
						<li class="nav-item"><a href="#tab1" class="active">投稿一覧</a></li>
						<li class="nav-item tab2"><a href="#tab2">フォロー</a></li>
						<li class="nav-item tab3"><a href="#tab3">フォロワー</a></li>
						<li class="nav-item"><a href="#tab4">いいね</a></li>
						<li class="nav-item"><a href="#tab5">アルバム</a></li>
					</ul>
				</div>
			</nav>
			<div id="tab-contents">
	        	<div id="tab1" class="tab">
	        		<%= render 'users/posts' %>
	        	</div>
	        	<div id="tab2" class="tab">
	        		<%= render 'users/following' %>
	        	</div>
	        	<div id="tab3" class="tab">
	        		<%= render 'users/followers' %>
	        	</div>
	        	<div id="tab4" class="tab">
	        		<%= render 'users/favorites' %>
	        	</div>
	        	<div id="tab5" class="tab">
	        		<%= render 'users/albums' %>
	        	</div>
	        </div>

		</div>
	</div>

	<%= render 'users/edit' %>

</div>

app/views/users/withdraw_view.html.erb
<div class="container withdraw">
	<div class="row">
		<div class="col-md-12">
			<h2>退会</h2>
		</div>
	</div>
	<div class="withdraw-box">
		<div class="row">
			<div class="col-md-offset-2 col-md-8">
				<h4> 退会されますとこのアカウントでのログインができなくなります（投稿は削除されません）。</h4>
				<h3><strong>本当に退会しますか？</strong></h3>
			</div>
		</div>
		<div class="row">
			<%= form_for(current_user, url:user_withdraw_path(current_user.id)) do |f| %>
				<div class="col-md-5">
					<%= link_to "いいえ", user_path(current_user.id), data: {"turbolinks" => false}, class:"btn btn-default btn-lg pull-right" %>
				</div>
				<div class="col-md-offset-2 col-md-5">
					<%= f.submit "はい", class:"btn btn-danger btn-lg pull-left", data:{confirm:"本当に退会しますか?"} %>
				</div>
			<% end %>
		</div>
	</div>
</div>