config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#top'

# Usersコントローラルーティング
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  get 'users/withdraw_view'
  patch '/users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
  patch '/users/:id/admin' => 'users#admin', as: 'user_admin'
  get '/users/admin_show' => 'users#admin_show', as: 'user_admin_show'
  resources :users, only: [:index, :show, :edit, :update]

# Postsコントローラルーティング
  get 'posts/top'
  get 'posts/about'
  get 'posts/hashtag'
  get 'posts/search_result'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
  end

# Albumsコントローラルーティング
  resources :albums, only: [:index, :show, :create, :destroy] do
    post 'posts/:id' => 'posts#album_in', as: 'posts_album_in'
    delete 'posts/:id' => 'posts#album_out', as: 'posts_album_out'
  end

# Roomsコントローラルーティング
  resources :rooms, only: [:index, :show, :create, :destroy]

# Contactsコントローラルーティング
  resources :contacts, only: [:new, :index, :show, :update, :create, :destroy]

# Relationshipsコントローラルーティング
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user

  has_many :post_albums, dependent: :destroy
  has_many :posts, through: :post_albums

  validates :name, presence: true, length: { maximum: 20 }
  validates :user_id, presence: true

  def album_in?(post)
    post_albums.where(post_id: post.id).exists?
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, only:[:create, :destroy]

  def index
  	@albums = Album.all.order(created_at: :desc)
  	@album = Album.new
		respond_to do |format|
		  format.html
		  format.js
	  end
  end

  def show
    @album = Album.find(params[:id])
    @albums = Album.where(user_id: @album.user.id).order(created_at: :desc)
  end

  def create
  	@albums = Album.all.order(created_at: :desc)
  	@album = Album.new(album_params)
  	@album.user_id = current_user.id
    @post = Post.find(session[:post_id].to_i)
  	if @album.save
	  	respond_to do |format|
	      format.html
	      format.js
	    end
      session[:post_id] = nil
  	else
      flash[:danger] = "アルバム名は1〜20文字で入力してください"
  		redirect_to post_path(@post.id)
  	end
  end

  def destroy
    @album = Album.find(params[:id])
    if @album.destroy
      flash[:success] = "アルバムを削除しました"
      redirect_to user_path(current_user.id)
    else
      flash.now[:danger] = "アルバムの削除に失敗しました"
      render :show
    end
  end

  private
  def album_params
  	params.require(:album).permit(:name, :user_id, {post_ids:[]})
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_create.html.erb
<% if user_signed_in? %>
	<% current_user.albums.order(created_at: :desc).each do |album| %>
		<%= link_to album_path(album.id), data: {"turbolinks" => false}, class:"album-link" do %>
			<div class="album-box">
				<div class="album-name">
				    <h3><%= album.name %></h3>
			    </div>
			    <div class="album-image">
					<%= attachment_image_tag album.posts.first, :post_image, :fill, 100, 100, format:"jpg", fallback:"/images/no_image.jpg", size:"100x100", alt:"ユーザイメージ" %>
			    </div>
			    <div class="album-post">
					<h4>計 <%= album.posts.count %> 枚</h4>
				</div>
				<% unless album.posts.include?(@post) %>
					<div class="album-in">
						<h5><%= link_to "このアルバムに追加", album_posts_album_in_path(album, @post), method: :post, data: {"turbolinks" => false}, class:"btn btn-default" %></h5>

					</div>
				<% else %>
				    <div class="album-exist">
						<h5>すでに追加されています</h5>
					</div>
				<% end %>
			</div>
		<% end %>
	<% end %>
<% end %>

app/views/albums/_index.html.erb
<div id="album-index" class="modal-text">
	<p class="pull-right"><a class="user-show-close" id="modal-close"><i class="fas fa-times"></i></a></p>
	<div class="container-fluid modal-box">
		<div class="row">
			<div class="col-md-5">
				<%= form_for(@album, remote: true) do |f| %>
					<h3 class="heading">アルバム作成</h3>
					<div class="field">
						<%= f.label :name, "タイトル" %>
						<%= f.text_field :name, autofocus: true, id:"album_text" %>
					</div>
					<div class="create-btn">
						<%= f.submit "作成", class:"btn-success-user" %>
					</div>
				<% end %>
			</div>

		    <div class="col-md-7" id="albums">
		    	<%= render partial: 'albums/create', locals: { post: @post, album: @album } %>
		    </div>
		</div>
	</div>
</div>

app/views/albums/create.js.erb
$('#albums').html("<%= j(render partial: 'albums/create', locals: { post: @post, album: @album } ) %>");
$("#album_text").val('')

app/views/albums/show.html.erb
<div class="container album-show">
	<div class="row">
		<div class="col-md-4 sidebar">
			<div class="album-user">
				<%= link_to user_path(@album.user.id), data: {"turbolinks" => false}, class:"album-user" do%>
					<%= attachment_image_tag @album.user, :profile_image, :fill, 80, 80, format:"jpg", fallback:"/images/no_image.jpg", size:"80x80", class:"img-circle", alt:"ユーザイメージ" %>
					<%= @album.user.name %>
				<% end %>
			</div>
			<% @albums.each do |album| %>
			    <%= link_to album_path(album.id), data: {"turbolinks" => false}, class:"album-link" do %>
					<div class="album-box">
						<div class="album-name">
						    <h2><%= album.name %></h2>
					    </div>
					    <div class="album-image">
					    	<% album.posts.first(2).each do |post| %>
							<%= attachment_image_tag post, :post_image, :fill, 100, 100, format:"jpg", fallback:"/images/no_image.jpg", size:"100x100", alt:"ポストイメージ" %>
							<% end %>
					    </div>
					    <div class="post-count">
							<h3>計 <%= album.posts.count %> 枚</h3>
						</div>
					</div>
				<% end %>
			<% end %>
		</div>
		<div class="col-md-offset-1 col-md-7">
			<h1 class="heading"><%= @album.name %></h1>
				<% if user_signed_in? %>
					<% if @album.user == current_user || current_user.admin == true %>
						<div class="col-md-offset-9 col-md-3 album-destroy">
							<%= link_to "このアルバムを削除", album_path(@album.id), method: :delete, data: {"turbolinks" => false}, class:"btn btn-default", data:{confirm:"本当にこのアルバムを削除しますか?"} %>
						</div>
					<% end %>
				<% end %>
			<% @album.posts.each do |post| %>
			    <div class="post-content">
					<%= link_to post_path(post.id), data: {"turbolinks" => false} do %>
						<%= attachment_image_tag post, :post_image, format:"jpg", fallback:"/images/no_image.jpg", class:"album-post", alt:"ポストイメージ" %>
					<% end %>

					<% if user_signed_in? %>
						<% if @album.user == current_user || current_user.admin == true %>
							<div class="col-md-offset-10 col-md-2 post-destroy">
								<%= link_to "削除", album_posts_album_out_path(@album, post), method: :delete, data: {"turbolinks" => false}, class:"btn-withdrawuser" %>
							</div>
						<% end %>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>