config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#top'

# Usersコントローラルーティング
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  get 'users/withdraw_view'
  patch '/users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
  patch '/users/:id/admin' => 'users#admin', as: 'user_admin'
  get '/users/admin_show' => 'users#admin_show', as: 'user_admin_show'
  resources :users, only: [:index, :show, :edit, :update]

# Postsコントローラルーティング
  get 'posts/top'
  get 'posts/about'
  get 'posts/hashtag'
  get 'posts/search_result'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
  end

# Albumsコントローラルーティング
  resources :albums, only: [:index, :show, :create, :destroy] do
    post 'posts/:id' => 'posts#album_in', as: 'posts_album_in'
    delete 'posts/:id' => 'posts#album_out', as: 'posts_album_out'
  end

# Roomsコントローラルーティング
  resources :rooms, only: [:index, :show, :create, :destroy]

# Contactsコントローラルーティング
  resources :contacts, only: [:new, :index, :show, :update, :create, :destroy]

# Relationshipsコントローラルーティング
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  attachment :post_image

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :iine_users, through: :favorites, source: :user, dependent: :destroy
  has_many :post_albums, dependent: :destroy
  has_many :albums, through: :post_albums

  validates :user_id, presence: true
  validates :favorites_count, presence: true
  validates :post_image, presence: true
  validates :title, length: { maximum: 16 }
  validates :text, length: { maximum: 1000 }

  def liked_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy, :album_in, :album_out, :hashtag]

  def top
    @late_posts = Post.order(created_at: :desc).all
    @trend_posts = Post.where(created_at: Time.now.beginning_of_month..Time.now.end_of_month).order("favorites_count" => :desc).all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if params[:back]
      render :new
    elsif @post.save
      flash[:success] = '投稿しました'
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def index
    @late_posts = Post.order(created_at: :desc).page(params[:late_page]).per(12)
    @trend_posts = Post.where(created_at: Time.now.beginning_of_month..Time.now.end_of_month).order("favorites_count" => :desc).page(params[:trend_page]).per(12)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def search_result
    @search_late_posts = @search.result(distinct: true).order(created_at: :desc).page(params[:search_late_page]).per(12)
    @search_trend_posts = @search.result(distinct: true).where(created_at: Time.now.beginning_of_month..Time.now.end_of_month).order("favorites_count" => :desc).page(params[:search_trend_page]).per(12)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @post = Post.find(params[:id])
    @albums = Album.all.order(created_at: :desc)
    @album = Album.new
    session[:post_id] = params[:id]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.user = current_user
      if @post.update(post_params)
        flash[:success] = '投稿を編集しました'
        redirect_to post_path(@post.id)
      else
        render :edit
      end
    else
      render :show
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.user = current_user
      post.destroy
      flash[:success] = '投稿を削除しました'
      redirect_to posts_path
    else
      render :show
    end
  end

  def album_in
    @post = Post.find(params[:id])
    @album = Album.find(params[:album_id])

    if @album.user = current_user
      unless @album.posts.include?(@post)
        @postalbum = PostAlbum.create(album_id: @album.id, post_id: @post.id)
        flash[:success] = 'アルバムに追加しました'
        redirect_to album_path(@album.id)
      else
        flash.now[:danger] = 'すでに追加されています'
        render :show, id: params[:id]
      end
    else
      render :show, id: params[:id]
    end
  end

  def album_out
    @album = Album.find(params[:album_id])
    @post = Post.find(params[:id])
    if @album.user = current_user
      @postalbum = PostAlbum.find_by(album_id: @album.id, post_id: @post.id)
      @postalbum.destroy
      flash[:success] = 'アルバムから削除しました'
      redirect_to album_path(@album.id)
    else
      render 'albums/show', id: params[:album_id]
    end
  end

  def hashtag
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :post_image, :title, :text, {album_ids:[]})
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_late_posts.html.erb
<% @late_posts.each do |post| %>
	<div class="col-md-4 index-post-box">
		<div class="post-img"><%= link_to post_path(post.id), data: {"turbolinks" => false} do %><%= attachment_image_tag post, :post_image, :fill, 300, 300, format: 'jpg', fallback:'/images/no_image.jpg', size:'300x300', alt:"ポストイメージ" %><% end %>
			<div class="post-title"><%= post.title %></div>
			<div class="post-user"><%= post.user.name %></div>
			<div class="post-like">
				<div id="late_likes_buttons_<%= post.id %>">
			    	<%= render partial: 'favorites/late_favorite', locals: {post: post} %>
			    </div>
			</div>
		</div>
	</div>
<% end %>
<div class="row" style="text-align: center;">
	<%= paginate @late_posts, :param_name => 'late_page', remote: true %>
</div>

app/views/posts/_late_search.html.erb
<% @search_late_posts.each do |post| %>
	<div class="col-md-4 index-post-box">
	    <div class="post-img"><%= link_to post_path(post.id), data: {"turbolinks" => false} do %><%= attachment_image_tag post, :post_image, :fill, 300, 300, format: 'jpg', fallback:'/images/no_image.jpg', size:'300x300', alt:"ポストイメージ" %><% end %>
			<div class="post-title"><%= post.title %></div>
			<div class="post-user"><%= post.user.name %></div>
			<div class="post-like">
				<div id="late_likes_buttons_<%= post.id %>">
			    	<%= render partial: 'favorites/late_favorite', locals: {post: post} %>
			    </div>
			</div>
	    </div>
	</div>
<% end %>
<div class="row" style="text-align: center;">
	<%= paginate @search_late_posts, :param_name => 'search_late_page', remote: true %>
</div>

app/views/posts/_trend_posts.html.erb
<% @trend_posts.each do |post| %>
	<div class="col-md-4 index-post-box">
		<div class="post-img"><%= link_to post_path(post.id), data: {"turbolinks" => false} do %><%= attachment_image_tag post, :post_image, :fill, 300, 300, format: 'jpg', fallback:'/images/no_image.jpg', size:'300x300', alt:"ポストイメージ" %><% end %>
		    <div class="post-title"><%= post.title %></div>
		    <div class="post-user"><%= post.user.name %></div>
		    <div class="post-like">
		      	<div id="trend_likes_buttons_<%= post.id %>">
		            <%= render partial: 'favorites/trend_favorite', locals: {post: post} %>
		        </div>
	      </div>
		</div>
	</div>
<% end %>
<div class="row" style="text-align: center;">
	<%= paginate @trend_posts, :param_name => 'trend_page', remote: true %>
</div>

app/views/posts/_trend_search.html.erb
<% @search_trend_posts.order("favorites_count" => :desc).each do |post| %>
	<div class="col-md-4 index-post-box">
		<div class="post-img"><%= link_to post_path(post.id), data: {"turbolinks" => false} do %><%= attachment_image_tag post, :post_image, :fill, 300, 300, format: 'jpg', fallback:'/images/no_image.jpg', size:'300x300', alt:"ポストイメージ" %><% end %>
		    <div class="post-title"><%= post.title %></div>
		    <div class="post-user"><%= post.user.name %></div>
		    <div class="post-like">
		      	<div id="trend_likes_buttons_<%= post.id %>">
		            <%= render partial: 'favorites/trend_favorite', locals: {post: post} %>
		        </div>
	      </div>
		</div>
	</div>
<% end %>
<div class="row" style="text-align: center;">
	<%= paginate @search_trend_posts, :param_name => 'search_trend_page', remote: true %>
</div>

app/views/posts/about.html.erb
<div class="container-fluid about">

	<div class="row">
		<div class="about-visual">
			<div class="col-md-offset-3 col-md-6">
				<div class="about-visual-text">
					<h2>すべてのアクアリストのための<br><br>
						コミュニティサイトです
					</h2>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<h1 class="heading">Functions</h1>
		</div>
		<div class="col-md-offset-3 col-md-6">
			<div class="about-post">
				<h2><i class="far fa-caret-square-right"></i> 投稿する</h2>
				<h4 class="text">右上のオレンジ色の投稿ボタンから自分のアクアリウム写真を投稿することができます。投稿する際はタイトルと説明文をつけられます。</h4>
			</div>
		</div>

		<div class="col-md-offset-3 col-md-6">
			<div class="about-room">
				<h2><i class="far fa-caret-square-right"></i> トークする</h2>
				<h4 class="text">ヘッダーの"Talk"ボタンからトークルームでリアルタイムチャットをすることができます。トーク一覧のページで新しくトークルームを作成することもできます。トークには節度を持って参加しましょう。</h4>
			</div>
		</div>

		<div class="col-md-offset-3 col-md-6">
			<div class="about-search">
				<h2><i class="far fa-caret-square-right"></i> 検索する</h2>
				<h4 class="text">ヘッダーの検索バーからみんなの投稿を検索できます。検索はタイトルと投稿の説明文に含まれている文字を検索します。気になるワードで検索してみてください。</h4>
			</div>
		</div>

		<div class="col-md-offset-3 col-md-6">
			<div class="about-like">
				<h2><i class="far fa-caret-square-right"></i> いいねする</h2>
				<h4 class="text">気に入った投稿にはいいねをすることができます。自分の投稿にいいねすることはできません。</h4>
			</div>
		</div>

		<div class="col-md-offset-3 col-md-6">
			<div class="about-album">
				<h2><i class="far fa-caret-square-right"></i> アルバムに追加する</h2>
				<h4 class="text">投稿をアルバムに追加することができます。お気に入りの投稿をまとめたり、自分の水槽の成長過程をまとめたりすることができます。</h4>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<h1 class="heading">Technologies</h1>
		</div>

		<div class="col-md-offset-2 col-md-2">
			<%= image_tag '/images/html.svg.png', size:"160x120", alt:"htmlロゴ" %>
		</div>
		<div class="col-md-2">
			<%= image_tag '/images/css3.png', size:"120x120", alt:"cssロゴ" %>
		</div>
		<div class="col-md-2">
			<%= image_tag '/images/rails.png', size:"180x120", alt:"railsロゴ" %>
		</div>
		<div class="col-md-2">
			<%= image_tag '/images/js2.svg', size:"180x120", alt:"jsロゴ" %>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<h1 class="heading">Auther</h1>
		</div>

		<div class="col-md-offset-3 col-6">
			<h2>Koichiro Matsumoto</h2>
		</div>
		<div class="col-md-offset-3 col-6 auther-info">
			<h4>hobby : 音楽鑑賞、ベースを弾く、バスケットボール、アクアリウム、ゲーム</h4>
			<h4>Github : <a href="https://github.com/koichiromatsumoto/">https://github.com/koichiromatsumoto/</a></h4>
		</div>
	</div>

</div>

app/views/posts/edit.html.erb
<div class="container post-edit">
	<div class="row">
		<div class="col-md-12">
			<h2 class="heading">編集画面</h2>
		</div>
	</div>
    <div class="post-box">
    	<%= form_for(@post) do |f| %>
    	<%= render 'layouts/error_messages', model: f.object %>

    	<div class="row post-img">
			<div class="col-md-12">
				<%= attachment_image_tag @post, :post_image, format:"jpg", fallback:"/images/no_image.jpg", class:"post-edit-img", alt:"ポストイメージ" %>
			</div>
		</div>

		<div class="row post-title">
			<div class="col-md-12">
				<%= f.label :title, "タイトル" %>
				<%= f.text_field :title, autocomplete: true, class:"form-control" %>
			</div>
		</div>

		<div class="row post-text">
			<div class="col-md-12">
				<%= f.label :text, "説明文" %>
				<%= f.text_area :text, autocomplete: true, class:"form-control" %>
			</div>
		</div>

		<div class="row edit-actions">
			<div class="col-md-offset-1 col-md-5">
				<%= f.submit "保存", class:"form btn-success-user" %>
			</div>
			<div class="col-md-5">
			    <%= link_to post_path(@post.id), method: :delete, data: {"turbolinks" => false}, class:"pull-right", data:{confirm:"本当に投稿を削除しますか?"} do %>
			        <button class="btn-post">投稿を削除</button>
			    <% end %>
			</div>
		</div>

		<% end %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container post-index">

    <div class="index-cont">
		<div class="row">
			<div class="col-md-offset-1 col-md-10">
				<div class="post-order">
					<ul id="tab-menu">
						<a href="#tab1" class="active"><li>新着</li></a>
						<a href="#tab2" class=""><li>トレンド</li></a>
						<li></li>
						<li></li>
			        </ul>
			    </div>
			</div>
		</div>

        <div id="tab-contents">
        	<div id="tab1" class="tab">
				<div class="row index-box late-posts">
					<div id="late_posts">
						<%= render partial: 'posts/late_posts', locals: {post: @late_posts} %>
					</div>
				</div>
			</div>

			<div id="tab2" class="tab">
				<div class="row index-box trend-posts">
					<div id="trend_posts">
						<%= render partial: 'posts/trend_posts', locals: {post: @trend_posts} %>
					</div>
				</div>
			</div>
		</div>

	</div>

</div>

app/views/posts/index.js.erb
$("#late_posts").html("<%= j(render partial: 'posts/late_posts', locals: {post: @late_posts}) %>");
$("#trend_posts").html("<%= j(render partial: 'posts/trend_posts', locals: {post: @trend_posts}) %>");

app/views/posts/new.html.erb
<div class="container post">
	<div class="row">
		<div class="col-md-12">
			<h2>投稿画面</h2>
		</div>
	</div>
    <div class="post-box">
    	<%= form_for @post, url:posts_path(@post.id) do |f| %>
    	<%= render 'layouts/error_messages', model: f.object %>

    	<div class="row post-img">
			<div class="col-md-12">
				<%= f.label :post_image, "写真選択" %>
				<div><img id="post_img_prev" src="#" class='hidden' ></div>
				<%= f.attachment_field :post_image, id:'post_img' %>
			</div>
		</div>

		<div class="row post-title">
			<div class="col-md-12">
				<%= f.label :title, "タイトル" %>
				<%= f.text_field :title, class:"form-control" %>
			</div>
		</div>

		<div class="row post-text">
			<div class="col-md-12">
				<%= f.label :text, "説明文" %>
				<%= f.text_area :text, class:"form-control" %>
			</div>
		</div>

		<div class="row">
			<div class="col-md-offset-9 col-md-2">
				<%= f.submit "投稿", class:"form btn-success-user" %>
			</div>
		</div>

		<% end %>
	</div>
</div>

app/views/posts/search_result.html.erb
<div class="container post-index">

    <div class="index-cont">
		<div class="row">
			<div class="col-md-offset-1 col-md-10">
				<div class="search-word">
					<h3>検索ワード：
			            <% if params[:q].present? && params[:q][:title_or_text_cont].present? %>
						    <%= params[:q][:title_or_text_cont] %>
						<% else %>
						    指定なし
						<% end %>
				    </h3>
				</div>
				<div class="post-order">
					<ul id="tab-menu">
						<a href="#tab1" class="active"><li>新着</li></a>
						<a href="#tab2" class=""><li>トレンド</li></a>
						<li></li>
						<li></li>
			        </ul>
			    </div>
			</div>
		</div>

        <div id="tab-contents">
        	<div id="tab1" class="tab">
        		<% if @search_late_posts.exists? %>
					<div class="row index-box late-posts">
						<div id="late_search">
							<%= render partial: 'posts/late_search', locals: {post: @late_search_posts} %>
						</div>
					</div>
				<% else %>
				    <div class="row">
				    	<div class="col-md-offset-1 col-md-10">
				    		<h3 class="search-nothing">検索結果はありません</h3>
				    	</div>
				    </div>
				<% end %>
			</div>

			<div id="tab2" class="tab">
				<% if @search_trend_posts.exists? %>
					<div class="row index-box trend-posts">
						<div id="trend_search">
							<%= render partial: 'posts/trend_search', locals: {post: @trend_search_posts} %>
						</div>
					</div>
				<% else %>
				    <div class="row">
				    	<div class="col-md-offset-1 col-md-10">
				    		<h3 class="search-nothing">検索結果はありません</h3>
				    	</div>
				    </div>
				<% end %>
			</div>
		</div>

	</div>

</div>

app/views/posts/search_result.js.erb
$("#late_search").html("<%= j(render partial: 'posts/late_search', locals: {post: @late_search_posts}) %>");
$("#trend_search").html("<%= j(render partial: 'posts/trend_search', locals: {post: @trend_search_posts}) %>");

app/views/posts/show.html.erb
<div class="container post-show">
    <div class="post-show-box" id="post-<%= @post.id %>" data-post-id="<%= @post.id %>">

    	<div class="row post-img">
			<div class="col-md-offset-2 col-md-8">
				<%= attachment_image_tag @post, :post_image, format:"jpg", fallback:"/images/no_image.jpg", class:"post-show-img", alt:"ポストイメージ" %>
			</div>
		</div>

		<div class="row post-menu">
		    <div class="col-md-offset-2 col-md-6">
		    	<h3>
		    		<%= link_to user_path(@post.user.id), data: {"turbolinks" => false}, class:"post-user" do%>
			    		<%= attachment_image_tag @post.user, :profile_image, :fill, 80, 80, format:"jpg", fallback:"/images/no_image.jpg", size: "80x80", class:"img-circle", alt:"ユーザイメージ" %>
			    		<%= @post.user.name %>
			   		<% end %>
			   	</h3>
		    </div>
			<div class="col-md-4">
				<div id="late_likes_buttons_<%= @post.id %>">
		            <%= render partial: 'favorites/late_favorite', locals: {post: @post} %>
		        </div>
		        <% if user_signed_in? %>
					<button class="btn btn-success" id="modal-open" data-target="album-index">アルバムに追加</button>
				<% end %>
					<p>投稿日：<%= @post.created_at.strftime('%Y/%m/%d %H:%M') %></p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-offset-2 col-md-8 post-title">
				<p><%= @post.title %></p>
			</div>

			<div class="col-md-offset-2 col-md-8 post-text">
				<p><%= @post.text %></p>
			</div>
        </div>

        <% if user_signed_in? %>
	        <% if @post.user == current_user || current_user.admin == true %>
				<div class="row">
					<div class="col-md-offset-9 col-md-2">
						<%= link_to "編集する", edit_post_path(@post.id), class:"btn-success-user", data: {"turbolinks" => false} %>
					</div>
				</div>
			<% end %>
		<% end %>

	</div>
</div>

<%= render partial: 'albums/index', locals: { post: @post, album: @album } %>

app/views/posts/top.html.erb
<div class="container-fluid top">

	<div class="row">
		<div class="main-visual">
			<div class="col-md-offset-3 col-md-6">
				<div class="main-visual-text">
					<h2>Communities for the aqualists<br><br>
					by the aqualists<br><br>
					of the aqualists.
					</h2>
				</div>
			</div>
			<div class="col-md-offset-4 col-md-4">
				<%= link_to "このサイトについて", posts_about_path, class:"btn-success-user", data: {"turbolinks" => false} %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-offset-2 col-md-8">
			<div class="post-order">
				<ul id="tab-menu">
					<a href="#tab1" class="active"><li>新着</li></a>
					<a href="#tab2" class=""><li>トレンド</li></a>
		        </ul>
		    </div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-offset-2 col-md-8">

	        <div id="tab-contents">
	        	<div id="tab1" class="tab">
					<div class="row index-box late-posts">
						<% @late_posts.first(9).each do |post| %>
						  <div class="col-md-4 index-post-box">
						    <div class="post-img"><%= link_to post_path(post.id), data: {"turbolinks" => false} do %><%= attachment_image_tag post, :post_image, :fill, 300, 300, format: 'jpg', fallback:'no_image.jpg', size:'300x300' %><% end %>
								<div class="post-title"><%= post.title %></div>
								<div class="post-user"><%= post.user.name %></div>
								<div class="post-like">
									<div id="late_likes_buttons_<%= post.id %>">
								    	<%= render partial: 'favorites/late_favorite', locals: {post: post} %>
								    </div>
								</div>
						    </div>
						  </div>
						<% end %>
					</div>
				</div>

				<div id="tab2" class="tab">
					<div class="row index-box trend-posts">
						<% @trend_posts.first(9).each do |post| %>
						<div class="col-md-4 index-post-box">
							<div class="post-img"><%= link_to post_path(post.id), data: {"turbolinks" => false} do %><%= attachment_image_tag post, :post_image, :fill, 300, 300, format: 'jpg', fallback:'no_image.jpg', size:'300x300' %><% end %>
							    <div class="post-title"><%= post.title %></div>
							    <div class="post-user"><%= post.user.name %></div>
							    <div class="post-like">
							      	<div id="trend_likes_buttons_<%= post.id %>">
							            <%= render partial: 'favorites/trend_favorite', locals: {post: post} %>
							        </div>
						      </div>
							</div>
						</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-offset-4 col-md-4 top-low">
			<%= link_to posts_path, class:"btn-success-user", data: {"turbolinks" => false} do %>すべての投稿一覧へ<% end %>
		</div>
	</div>

</div>