config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#top'

# Usersコントローラルーティング
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  get 'users/withdraw_view'
  patch '/users/:id/withdraw' => 'users#withdraw', as: 'user_withdraw'
  patch '/users/:id/admin' => 'users#admin', as: 'user_admin'
  get '/users/admin_show' => 'users#admin_show', as: 'user_admin_show'
  resources :users, only: [:index, :show, :edit, :update]

# Postsコントローラルーティング
  get 'posts/top'
  get 'posts/about'
  get 'posts/hashtag'
  get 'posts/search_result'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
  end

# Albumsコントローラルーティング
  resources :albums, only: [:index, :show, :create, :destroy] do
    post 'posts/:id' => 'posts#album_in', as: 'posts_album_in'
    delete 'posts/:id' => 'posts#album_out', as: 'posts_album_out'
  end

# Roomsコントローラルーティング
  resources :rooms, only: [:index, :show, :create, :destroy]

# Contactsコントローラルーティング
  resources :contacts, only: [:new, :index, :show, :update, :create, :destroy]

# Relationshipsコントローラルーティング
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <% model.errors.full_messages.each do |message| %>
        <div id="alert" class="alert-dismissible alert alert-danger col-md-offset-3 col-md-6" >
			<a class="close" data-dismiss="alert" aria-label="Close">×</a>
			<%= message %>
		</div>
    <% end %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
	<div id="alert" class="col-md-offset-3 col-md-6 alert alert-<%= message_type %> alert-dismissible" >
		<a class="close" data-dismiss="alert" aria-label="Close">×</a>
		<%= message %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aquel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <header>
      <nav class="navbar navbar-fixed-top">
        <div class="container-fluid">
          <div class="row">

            <!-- ロゴ -->
          <div class="col-md-2 navbar-logo">
            <%= link_to root_path, class: "navbar-logo-box", data: {"turbolinks" => false} do %>
              <%= image_tag "/images/logo.png", class:"logo", alt:"ロゴマーク" %>
            <% end %>
          </div>

          <div class="col-md-6 navbar-search search">
            <%= search_form_for @search, url: posts_search_result_path, class:"form-inline" do |f| %>
              <%= f.search_field :title_or_text_cont, class:"form-control field", placeholder:"検索ワードを入力してください" %>
              <span class="input-group-btn"><%= button_tag sanitize('<i class="glyphicon glyphicon-search"></i>'), :type => "submit",:class =>"btn  btn-success search-btn" %></span>
            <% end %>
          </div>

          <!-- 右側リンク -->
          <div class="col-md-4 navbar-item">

            <% if user_signed_in? && current_user.admin == false %><!--ユーザがログインしたとき-->

              <div class="nav navbar-nav pull-right nav-menu">
                <%= link_to destroy_user_session_path, method: :delete, data: {"turbolinks" => false}, class:"nav-menu-item" do%>
                  <div class="nav-item-box pull-right">
                  <i class="fas fa-sign-out-alt"></i> Log out</div>
                <% end %>
                <%= link_to user_path(current_user.id), data: {"turbolinks" => false}, class:"nav-menu-item" do%>
                  <div class="nav-item-box pull-right">
                  <i class="fas fa-user-alt"></i> My page</div>
                <% end %>
                <%= link_to rooms_path, data: {"turbolinks" => false}, class:"nav-menu-item" do%>
                  <div class="nav-item-box pull-right">
                  <i class="fas fa-comment-dots"></i> Talk</div>
                <% end %>
              </div>

            <% elsif user_signed_in? && current_user.admin == true %> <!--adminのとき-->

                <div class="nav navbar-nav pull-right nav-menu">
                  <%= link_to destroy_user_session_path, method: :delete, data: {"turbolinks" => false}, class:"nav-menu-item" do%>
                    <div class="nav-item-box pull-right">
                    <i class="fas fa-sign-out-alt"></i> Log out</div>
                  <% end %>
                  <%= link_to user_path(current_user.id), data: {"turbolinks" => false}, class:"nav-menu-item" do%>
                    <div class="nav-item-box pull-right">
                    <i class="fas fa-user-alt"></i> My page</div>
                  <% end %>
                  <%= link_to rooms_path, data: {"turbolinks" => false}, class:"nav-menu-item" do%>
                    <div class="nav-item-box pull-right">
                    <i class="fas fa-comment-dots"></i> Talk</div>
                  <% end %>
                </div>

            <% else %><!-- ゲストユーザのとき -->

              <div class="nav navbar-nav pull-right nav-menu">
                <%= link_to new_user_registration_path, data: {"turbolinks" => false}, class:"nav-menu-item" do%>
                  <div class="nav-item-box pull-right">
                  <i class="fas fa-user-plus"></i> New</div>
                <% end %>
                <%= link_to new_user_session_path, data: {"turbolinks" => false}, class:"nav-menu-item" do%>
                  <div class="nav-item-box pull-right">
                  <i class="fas fa-sign-in-alt"></i> Log in</div>
                <% end %>
                <%= link_to rooms_path, data: {"turbolinks" => false}, class:"nav-menu-item" do%>
                  <div class="nav-item-box pull-right">
                  <i class="fas fa-comment-dots"></i> Talk</div>
                <% end %>
              </div>

            <% end %>

          </div>

          </div>
        </div>
      </nav>
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-offset-10 col-md-2">
            <%= link_to new_post_path, data: {"turbolinks" => false} do %>
              <div class="post-btn">
                <div class="i-plus"><i class="fas fa-plus"></i></div>
                <div class="i-images"><i class="fas fa-images"></i></div>
              </div>
            <% end %>
          </div>
        </div>
    </header>

    <%= render 'layouts/flash_messages' %>

    <%= yield %>


    <footer>
      <nav class="navbar navbar-fixed-bottom">
        <div class="container-fluid">
          <div class="row">

            <div class="col-md-offset-4 col-md-4 col-sm-offset-2 col-sm-8 footer-item">
              <%= link_to posts_about_path, data: {"turbolinks" => false}, class:"footer-menu" do%>
                <div class="footer-menu-item pull-left">
                <i class="fas fa-tint"></i> About</div>
              <% end %>

              <% if user_signed_in? && current_user.admin == false %><!--ユーザがログインしたとき-->
                <%= link_to new_contact_path, data: {"turbolinks" => false}, class:"footer-menu" do%>
                  <div class="footer-menu-item pull-right">
                  <i class="fas fa-envelope"></i> Contact</div>
                <% end %>
              <% elsif user_signed_in? && current_user.admin == true %> <!--adminのとき-->
                <%= link_to contacts_path, data: {"turbolinks" => false}, class:"footer-menu" do%>
                  <div class="footer-menu-item pull-right">
                  <i class="fas fa-envelope"></i> Contact</div>
                <% end %>
              <% else %><!-- ゲストユーザのとき -->
                <%= link_to new_user_session_path, data: {"turbolinks" => false}, class:"footer-menu" do%>
                  <div class="footer-menu-item pull-right">
                  <i class="fas fa-envelope"></i> Contact</div>
                <% end %>
              <% end %>
            </div>

          </div>
        </div>
      </nav>
    </footer>

  </body>
</html>